title = "Title"

[params.author]
name = "Name"
image = "img/author.jpg"
headline = "Unidentified life form"
bio = "A little bit about me"
links = [cd .cd
  { twitter = "https://twitter.com/username" }
]
